version: "3.8"
services:
  alv_shit:
    ipc: host
    # ports:
    #   - "8869:8869"
    #   - "8870:8870"
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: "alv/alv_shit:debug"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]
    tty: true 
    volumes:
      - /home/ch35li/ehr/embeddings_exp:/exp
